apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: digilians-backend
subjects:
  - kind: ServiceAccount
    name: app-sa
    namespace: digilians-backend
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: digilians-frontend
subjects:
  - kind: ServiceAccount
    name: app-sa
    namespace: digilians-frontend
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
